### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by danielkanzel** [KraXarN/KraxbotOSS#14]
HI,
Where I can donate for your KraxbotOSS?
Please, add to readme.

**Comment by KraXarN** [comment]
You can use [this link](https://www.paypal.me/kraxie) to donate to my Paypal if you want to. I might set up a more permanent link or something similar if more people want to donate.

Thanks for your support! :smile_cat:

**Comment by danielkanzel** [comment]
OK, thanks)

**Comment by danielkanzel** [comment]
Used this, sometimes i will drop you some cash. Thanks for your work.
