### ISSUE TITLE
[Bug] Chatroom settings crashed

### ISSUE THREAD

**Issue by danielkanzel** [KraXarN/KraxbotOSS#18]
Way:
1. Login
2. Go to the settings
3. Go to chatrooms
4. Choose one group
5. Click Save
6. 
![image](https://cloud.githubusercontent.com/assets/26162864/25744577/4dda7e8c-31a3-11e7-8138-87b751cecaf4.png)
Sorry for russian, try to translate:
Длина параметров не может быть меньше нуля = Lenght of parameter can't be more then null
Имя параметра = Name of parameter

**Comment by KraXarN** [comment]
Have you updated to 1.0.1?

**Comment by danielkanzel** [comment]
Yes
