### ISSUE TITLE
Crash: No Cleverbot session for chatgroup

### ISSUE THREAD

**Issue by danielkanzel** [KraXarN/KraxbotOSS#20]
![image](https://cloud.githubusercontent.com/assets/26162864/25915303/c6565a3c-35c9-11e7-8123-1f1106e0d080.png)
Crashed, i don't know why. Maybe cleverbot bug.

**Comment by KraXarN** [comment]
When does it crash?

**Comment by danielkanzel** [comment]
Don't know, i try to repeat this crash
