### ISSUE TITLE
[Bug] Connects to few of chatgroups

### ISSUE THREAD

**Issue by danielkanzel** [KraXarN/KraxbotOSS#21]
I have 5 groups in autoconnect
![image](https://cloud.githubusercontent.com/assets/26162864/25951204/a656d4e0-3665-11e7-91a4-f3e87fadd4e9.png)
When I start bot, it connects to random 1-3 of them.
![image](https://cloud.githubusercontent.com/assets/26162864/25951249/c355edf6-3665-11e7-8e98-a503814706ff.png)
![image](https://cloud.githubusercontent.com/assets/26162864/25951259/cf462ea0-3665-11e7-83cb-698ac7b72251.png)
![image](https://cloud.githubusercontent.com/assets/26162864/25951283/d9f6d8d6-3665-11e7-968d-7a2f24d60a95.png)

**Comment by KraXarN** [comment]
If you open settings, can you see the chatrooms which aren't being joined there and are they checked?

**Comment by danielkanzel** [comment]
![image](https://cloud.githubusercontent.com/assets/26162864/25955606/69531484-3672-11e7-992e-b56f0ef1ff37.png)
Yes

**Comment by danielkanzel** [comment]
UPD
It connects to all chat groups but not show them in panel

**Comment by danielkanzel** [comment]
1.0.3
fixed
maybe its really Steam problem...

**Comment by KraXarN** [comment]
Maybe, but I did some various fixes that might have been the cause of the issue.

**Comment by danielkanzel** [comment]
Maybe =)
